# Nome del workflow
name: Mirror to GitHub

# Trigger del workflow: si attiva a ogni push
on: push


jobs:
  mirror:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del repository sorgente (Gitea)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurazione Git e push su GitHub
        run: |
          # Configura l'identità dell'utente Git
          git config --global user.email "gitea-actions-bot@gitea.com"
          git config --global user.name "Gitea Actions"

          # Aggiunge il repository GitHub come un "remote"
          # Utilizza il secret di Gitea per l'autenticazione con il PAT di GitHub
          git remote add github https://Asso360:${{ secrets.GITHUB_TOKEN }}@github.com/Asso360/Open360-API-schema.git

          # Esegue il push in modalità "mirror"
          git push --mirror github