openapi: 3.1.0
info:
  title: Open360 app API
  version: 1.0.0
  description: API per tutte le richieste inerenti l'app

servers:
  - url: https://open360.it

paths:
  /app/v1/register:
    post:
      summary: Registra un nuovo utente
      description: Usata solo dalla LoginFunction con accesso privilegiato.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Utente registrato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Richiesta non valida
        '401':
          description: Non autorizzato
        '500':
          description: Errore interno

  /app/v1/notifyCode:
    post:
      summary: Invia email con il codice OTP
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotifyCodeRequest'
      responses:
        '200':
          description: Codice inviato con successo
        '400':
          description: Richiesta non valida
        '401':
          description: Non autorizzato
        '500':
          description: Errore interno

  /app/v1/updateUserProfile:
    post:
      summary: Aggiorna i dati del profilo utente
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileDataRequest'
      responses:
        '200':
          description: Dati aggiornati con successo
        '400':
          description: Richiesta non valida
        '401':
          description: Non autorizzato
        '500':
          description: Errore interno

  /app/v1/Enrollment:
    post:
      summary: Permette all'utente di inserire una nuova iscrizione a corso/evento dall'app
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertEnrollmentRequest'
      responses:
        '200':
          description: Iscrizione registrata con successo
        '400':
          description: Richiesta non valida
        '401':
          description: Non autorizzato
        '500':
          description: Errore interno



components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      properties:
        idSoggetto:
          type: string
        idCentro:
          type: string
        email:
          type: string
          format: email

    RegisterResponse:
      type: object
      properties:
        idUtente:
          type: string
      required:
        - idUtente

    NotifyCodeRequest:
      type: object
      properties:
        code:
          type: string
        email:
          type: string
          format: email
      required:
        - code
        - email

    UpdateProfileDataRequest:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        fiscalCode:
          type: string
      required:
        - id
        - firstName
        - lastName
        - email

    InsertEnrollmentRequest:
      type: object
      properties:
        activityId:
          type: string
          description: ID of the activity
        centerId:
          type: string
          description: ID of the center
        registeredUser:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            fiscalCode:
              type: string
            address:
              $ref: '../schemas/firestore.yaml#/components/schemas/Address'
          description: Data of the registered user
        customOptions:
          type: array
          items:
            type: object
            properties:
              optionId:
                type: string
                description: ID of the option (e.g., Shift choice)
              selectedValue:
                type: integer
                description: Value chosen for the option (e.g., Shift1)
          description: Custom options that may affect the price
        chosenServices:
          type: array
          items:
            type: object
            properties:
              serviceId:
                type: string
              quantity:
                type: integer
          description: Additional services chosen
        installmentPlan:
          type: object
          properties:
            id:
              type: string
              description: ID of the payment installment plan chosen by the user
          description: Payment installment plan
        paymentMethod:
          type: object
          properties:
            id:
              type: number
            description:
              type: string
            type:
              type: string
              enum:
                - pay at center
                - pay in App
                - bank transfer
          description: Payment method
        notes:
          type: string
          description: Additional notes for the booking
        moduleAcceptances:
          type: array
          items:
            type: object
            properties:
              acceptedModuleId:
                type: string
                description: ID of the accepted policy
          description: Accepted modules and policies
        billingDetails:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            fiscalCode:
              type: string
            address:
              $ref: '../schemas/firestore.yaml#/components/schemas/Address'
            phoneNumber:
              type: string
          description: Billing details
      required:
        - activityId
        - centerId
        - registeredUser
        - paymentMethod
